name: Build

on:
  push:
    branches: [ main, prettyprint ]
    tags:
      - v*
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build:
    uses: benjamin-hodgson/BuildScripts/.github/workflows/dotnet.yml@main
    with:
      DOCS_FOLDER: Gutenberg.Docs
    secrets:
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
